name: build-debian

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create_tarball
      run: |
           cd ..
           tar --exclude=.git -cvzf packetsender_0.1+testonly.orig.tar.gz PacketSender
    - name: create_debian_dir
      run: |
           cp -a .github/workflows/debian .
    - name: install_dependencies
      run: |
           sudo apt install cmake debhelper devscripts qttools5-dev
    - name: build
      run: |
           debuild --no-lintian --no-sign
    - name: Upload Test Build Artifact
      if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name != 'master' && github.ref_name != 'development' }}
      uses: actions/upload-artifact@v2
      with:
        retention-days: 5
        name: packetsender-testbuild-${{ github.ref_name }}
        path: obj-x86_64-linux-gnu/PacketSender
